### PR TITLE
github.com:jojessf/perl-Amazon-S3 Init

### PR DESCRIPTION
**Pull request by jojessf**
add ` $Bucket->copy_key( $inkey, $newkey )` <3

### CODE REVIEW

**Comment by rlauer6** [comment]
Hi! Thanks for the PR!....I'll incorporate this into the next version, however I will be making a few changes to satisfy `perlcritic` ... also `README.md` is autogenerated from the pod.  Thanks again!

**Comment by rlauer6** [comment]
Spent some time today looking at the `CopyObject` request API.  I think we can beef up `copy_key` a bit so that it allows for more flexible exercising of that API.

New branch `copy_object` pushed this morning...check out the documentation in `Amazon::S3::Bucket` for `copy_object` and see what you think.  I've also added a very basic unit test for `copy_object()` in `t/01-api.t`.

**Comment by rlauer6** [comment]
As I have not gotten any feedback, I am incorporating the new `copy_object()` method into the new 0.59 version and closing this PR.

**Comment by jojessf** [comment]
Have been unfortunately busy.  I like your implementation of copy_object, and it does what it needs to do.   Copies an object, optionally between buckets.

Did spend a bit of time considering it, but I do not have anything tangible to offer at this time.  Would like convenience methods for "x-amz-copy-source-if-modified-since" & "x-amz-copy-source-if-match" - but I haven't had the time to figure out how to get those to actually work just yet.  Also want convenience methods to add tags, inhibit tag inheritance, inhibit the inheritance of specific tags - but haven't tested any of that.

Might come back with another PR when I have more time to put into this - if that's okay with you, of course.  

Thank you, rlauer6!  =>

**Pull request closed without merging**
