### PR TITLE
Restore missing dep XML::Simple needed by main module

### PR DESCRIPTION
**Pull request by toddr**

### CODE REVIEW

**Comment by toddr** [comment]
NOTE: you have issues disabled in this repo but are claiming github as your issue tracker in metacpan. Could the issues be turned on here?

**Comment by toddr** [comment]
@eserte: FIRST!

**Comment by rlauer6** [comment]
> NOTE: you have issues disabled in this repo but are claiming github as your issue tracker in metacpan. Could the issues be turned on here?

Thanks - turned on now

**Comment by rlauer6** [comment]
> _ No description provided. _

Yup...missed that. I wanted to replace XML::Simple with XML::LibXML::Simple - planning on a .55 release to address some other issues introduced by merging in changes to support signature V4...thanks for the PR

**Comment by toddr** [comment]
Additionally... Test::Output is being depended on for Runtime but I assume it's only there for test purposes. https://metacpan.org/release/BIGFOOT/Amazon-S3-0.54/source/META.json

This repo is setup a little strangely for a CPAN module so I'm having trouble suggesting a patch for it.

**Comment by rlauer6** [comment]
> Additionally... Test::Output is being depended on for Runtime but I assume it's only there for test purposes. https://metacpan.org/release/BIGFOOT/Amazon-S3-0.54/source/META.json#L45
> 
> This repo is setup a little strangely for a CPAN module so I'm having trouble suggesting a patch for it.

Thanks Todd - added that to the new release (0.55) that I just pushed up - just a heads up to you and Tim that I think the setting of the signer to us-east-1 is not correct - if the behavior you're looking for is so that the `buckets()` method uses the default region (us-east-1) then I think it best to embed that in the `buckets()` method.  When users instantiate the S3 object they will most likely be setting the region in which their bucket of interest resides.  I've run the test suite on this version but thougth I'd wait to see if you guys have any comments before pushing it to CPAN.  Also when Tim added V4 signing, he neglected to pass the option security token - that is also corrected in this version.

**Comment by timmullin** [comment]
I suspect that may break things; I'll have to look further at those changes.

**Comment by rlauer6** [comment]
> I suspect that may break things; I'll have to look further at those changes.
> […](#)

Typically the module is used to access a bucket or object within the bucket, so a user would normally want to specify the region or use the region specified in his configuration since the bucket is region specific.  By setting the signer do us-east-1 as the default you force the user to use adjust_region() if they want to perform their most likely goals (retrieve, store objects).  Maybe I'm missing something important here?   But the use case of listing buckets is not the common one - so it made sense to me to reset the region to us-east-1 for just that operation (GET /).  Again, I may be missing something important or you have a use case that requires that us-east-1 be the default - in which case you can pass that in to the constructor.

**Comment by timmullin** [comment]
In our case, we don't know what the region is.  This information was not
required with our original implementation using the V2 signatures.  So we
have to start off using the default region, then discover the real region
using adjust_region.  An alternative, for a more general use case, would be
to let the caller optionally pass in a region as one of the constructor
options.  If they pass in a region, use that; otherwise use the default.

**Comment by rlauer6** [comment]
> In our case, we don't know what the region is. This information was not required with our original implementation using the V2 signatures. So we have to start off using the default region, then discover the real region using adjust_region. An alternative, for a more general use case, would be to let the caller optionally pass in a region as one of the constructor options. If they pass in a region, use that; otherwise use the default.

The constructor can be passed `region` - apparently I forgot to document that.

**Comment by rlauer6** [comment]
> > In our case, we don't know what the region is. This information was not required with our original implementation using the V2 signatures. So we have to start off using the default region, then discover the real region using adjust_region. An alternative, for a more general use case, would be to let the caller optionally pass in a region as one of the constructor options. If they pass in a region, use that; otherwise use the default.
> 
> The constructor can be passed `region` - apparently I forgot to document that. Whoops, actually I did - in the documentation for the `new()` method.

I guess my concern is that setting the signer initially to us-east-1 is fine if your bucket is in us-east-1 and as you stated setting the region to us-east-1 supports listing all of your buckets.  If your bucket is not in us-east-1 the user of the module *must* call `adjust_region()` themselves before attempting to retrieve or store objects.  Do I understand that properly?  Since it was not necessary to use a region for V2 and the module now ONLY supports V4 wouldn't that break existing applications?  Or at least it should be documented that if your bucket is not in us-east-1 you must call `adjust_region()` before other API calls.

**Comment by timmullin** [comment]
At the time V4 support was implemented it seemed that the upstream CPAN project would never become live again.  When multi-part upload was developed we pinged the maintainer and he never responded.  V4 support was done years later.  It should be documented; I never did that because it was initially developed for internal use.

**Comment by rlauer6** [comment]
You are probably aware that the `get_location_constraint()` method will return the region the bucket is in? Perhaps the approach then should be to set the default region to `us-east-1` as you've done in your PR (if the caller does not provide a region) AND support an option on `Amazon::S3::Bucket` to set the region...if the region differs from the region set in the S3 object, then call `adjust_region()`?  If no region is set in the constructor, call `get_location_constraint()` and proceed with the same logic - call `adjust_region()` if the region of the S3 object differs.  This means that the constructor for the bucket object will incur the penalty of the lookup only if the caller does not set the region or the region differs from `us-east-1`.

**Comment by rlauer6** [comment]
updated in latest master

**Pull request closed without merging**
